# netlify.toml
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  command = "cd cyberpunk-mana-interface (2) && npm install && npm run build"
  publish = "cyberpunk-mana-interface (2)/.next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"