# netlify.toml
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  command = "echo 'No build command needed'"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"